const randumNumber = (number)=>{
   return Math.floor(Math.random() * number)
}

export const data = [
    {
        id:1,
        logo:'MB',
        name:'MacBook 15" 250 SSD 12GB',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'01:00',
        status:'Reconciled',
    },
    {
        id:2,
        logo:'MB',
        name:' Apple MacBook 15" 250 SSD 12GB',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'01:30',
        status:'Pending',
    },
    {
        id:3,
        logo:'SG',
        name:'Samsung Galaxy S22 Ultra',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'02:00',
        status:'Reconciled',
    },
    {
        id:4,
        logo:'SG',
        name:'Iphone 13 Pro Max',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'02:30',
        status:'Pending',
    },
    {
        id:5,
        logo:'IP',
        name:'Iphone XS Max',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'03:00',
        status:'Reconciled',
    },
    {
        id:6,
        logo:'TC',
        name:'Tecno Camon 16',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'03:30',
        status:'Un-reconciled',
    },
    {
        id:7,
        logo:'TC',
        name:'Tecno Pouvoir 4',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'04:00',
        status:'Un-reconciled',
    },
    {
        id:8,
        logo:'HP',
        name:'HP Elitebook 840',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'04:30',
        status:'Reconciled',
    },
    {
        id:9,
        logo:'HP',
        name:'HP Elitebook 820',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'05:00',
        status:'Pending',
    },
    {
        id:10,
        logo:'HP',
        name:'HP Laserjet Printer 820',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'05:30',
        status:'Un-reconciled',
    },
    {
        id:11,
        logo:'SG',
        name:'Samsung Galaxy S9',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'12:00',
        status:'Pending',
    },
    {
        id:12,
        logo:'SG',
        name:'Samsung Galaxy Note 9',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'12:30',
        status:'Reconciled',
    },
    {
        id:13,
        logo:'HW',
        name:'Huawei P9 4G LTE',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'01:00',
        status:'Un-reconciled',
    },
    {
        id:14,
        logo:'HW',
        name:'Huawei Nova 9',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'01:30',
        status:'Un-reconciled',
    },
    {
        id:15,
        logo:'IP',
        name:'Iphone 12',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'02:00',
        status:'Reconciled',
    },
    {
        id:16,
        logo:'IP',
        name:'Iphone 6s',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'02:30',
        status:'Un-reconciled',
    },
    {
        id:17,
        logo:'RL',
        name:'10.2 Inch Ringlight',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'03:00',
        status:'Pending',
    },
    {
        id:18,
        logo:'AP',
        name:'Airpods',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'03:30',
        status:'Reconciled',
    },
    {
        id:19,
        logo:'OR',
        name:'20,000 MAh Oraimo Power Bank',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'04:00',
        status:'Pending',
    },
    {
        id:20,
        logo:'OR',
        name:'Oraimo 2mm USB Cable',
        price:randumNumber(80000),
        transaction__no:randumNumber(200000000),
        time:'04:30',
        status:'Reconciled',
    }
    
]